//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalMoneyManagementAndPlanning.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalMoneyManagementAndPlanning.Resources.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountEN {
            get {
                return ResourceManager.GetString("AccountEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap.
        /// </summary>
        internal static string AccountTR {
            get {
                return ResourceManager.GetString("AccountTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Added.
        /// </summary>
        internal static string AddAccountSuccesfulEN {
            get {
                return ResourceManager.GetString("AddAccountSuccesfulEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Eklendi.
        /// </summary>
        internal static string AddAccountSuccesfulTR {
            get {
                return ResourceManager.GetString("AddAccountSuccesfulTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddEN {
            get {
                return ResourceManager.GetString("AddEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Added.
        /// </summary>
        internal static string AddExpenseSuccesfulEN {
            get {
                return ResourceManager.GetString("AddExpenseSuccesfulEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider Eklendi.
        /// </summary>
        internal static string AddExpenseSuccesfulTR {
            get {
                return ResourceManager.GetString("AddExpenseSuccesfulTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Added.
        /// </summary>
        internal static string AddIncomeSuccesfulEN {
            get {
                return ResourceManager.GetString("AddIncomeSuccesfulEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelir Eklendi.
        /// </summary>
        internal static string AddIncomeSuccesfulTR {
            get {
                return ResourceManager.GetString("AddIncomeSuccesfulTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string AddTR {
            get {
                return ResourceManager.GetString("AddTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string AllEN {
            get {
                return ResourceManager.GetString("AllEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        internal static string AllTR {
            get {
                return ResourceManager.GetString("AllTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountEN {
            get {
                return ResourceManager.GetString("AmountEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        internal static string AmountTR {
            get {
                return ResourceManager.GetString("AmountTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string AprilEN {
            get {
                return ResourceManager.GetString("AprilEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nisan.
        /// </summary>
        internal static string AprilTR {
            get {
                return ResourceManager.GetString("AprilTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string AugustEN {
            get {
                return ResourceManager.GetString("AugustEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağustos.
        /// </summary>
        internal static string AugustTR {
            get {
                return ResourceManager.GetString("AugustTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackEN {
            get {
                return ResourceManager.GetString("BackEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        internal static string BackTR {
            get {
                return ResourceManager.GetString("BackTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        internal static string BankAccountEN {
            get {
                return ResourceManager.GetString("BankAccountEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Hesabı.
        /// </summary>
        internal static string BankAccountTR {
            get {
                return ResourceManager.GetString("BankAccountTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Card.
        /// </summary>
        internal static string BankCardEN {
            get {
                return ResourceManager.GetString("BankCardEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Kartı.
        /// </summary>
        internal static string BankCardTR {
            get {
                return ResourceManager.GetString("BankCardTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        internal static string BillEN {
            get {
                return ResourceManager.GetString("BillEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        internal static string BillTR {
            get {
                return ResourceManager.GetString("BillTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelEN {
            get {
                return ResourceManager.GetString("CancelEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string CancelTR {
            get {
                return ResourceManager.GetString("CancelTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string CashEN {
            get {
                return ResourceManager.GetString("CashEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit.
        /// </summary>
        internal static string CashTR {
            get {
                return ResourceManager.GetString("CashTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryEN {
            get {
                return ResourceManager.GetString("CategoryEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string CategoryTR {
            get {
                return ResourceManager.GetString("CategoryTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity.
        /// </summary>
        internal static string CharityEN {
            get {
                return ResourceManager.GetString("CharityEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağış.
        /// </summary>
        internal static string CharityTR {
            get {
                return ResourceManager.GetString("CharityTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        internal static string ClothingEN {
            get {
                return ResourceManager.GetString("ClothingEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giyim.
        /// </summary>
        internal static string ClothingTR {
            get {
                return ResourceManager.GetString("ClothingTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CreditCardEN {
            get {
                return ResourceManager.GetString("CreditCardEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kartı.
        /// </summary>
        internal static string CreditCardTR {
            get {
                return ResourceManager.GetString("CreditCardTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string CreditEN {
            get {
                return ResourceManager.GetString("CreditEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi.
        /// </summary>
        internal static string CreditTR {
            get {
                return ResourceManager.GetString("CreditTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CurrencyEN {
            get {
                return ResourceManager.GetString("CurrencyEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim.
        /// </summary>
        internal static string CurrencyTR {
            get {
                return ResourceManager.GetString("CurrencyTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateEN {
            get {
                return ResourceManager.GetString("DateEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DateOfBirthEN {
            get {
                return ResourceManager.GetString("DateOfBirthEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        internal static string DateOfBirthTR {
            get {
                return ResourceManager.GetString("DateOfBirthTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        internal static string DateTR {
            get {
                return ResourceManager.GetString("DateTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string DayEN {
            get {
                return ResourceManager.GetString("DayEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün.
        /// </summary>
        internal static string DayTR {
            get {
                return ResourceManager.GetString("DayTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string DecemberEN {
            get {
                return ResourceManager.GetString("DecemberEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aralık.
        /// </summary>
        internal static string DecemberTR {
            get {
                return ResourceManager.GetString("DecemberTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionEN {
            get {
                return ResourceManager.GetString("DescriptionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string DescriptionTR {
            get {
                return ResourceManager.GetString("DescriptionTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        internal static string DistributionEN {
            get {
                return ResourceManager.GetString("DistributionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dağılım.
        /// </summary>
        internal static string DistributionTR {
            get {
                return ResourceManager.GetString("DistributionTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning.
        /// </summary>
        internal static string EarningEN {
            get {
                return ResourceManager.GetString("EarningEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazanç.
        /// </summary>
        internal static string EarningTR {
            get {
                return ResourceManager.GetString("EarningTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        internal static string EducationEN {
            get {
                return ResourceManager.GetString("EducationEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğitim.
        /// </summary>
        internal static string EducationTR {
            get {
                return ResourceManager.GetString("EducationTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Bill.
        /// </summary>
        internal static string ElectricityBillEN {
            get {
                return ResourceManager.GetString("ElectricityBillEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektrik Faturası.
        /// </summary>
        internal static string ElectricityBillTR {
            get {
                return ResourceManager.GetString("ElectricityBillTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailEN {
            get {
                return ResourceManager.GetString("EmailEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta.
        /// </summary>
        internal static string EmailTR {
            get {
                return ResourceManager.GetString("EmailTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        internal static string EntertainmentEN {
            get {
                return ResourceManager.GetString("EntertainmentEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eğlence.
        /// </summary>
        internal static string EntertainmentTR {
            get {
                return ResourceManager.GetString("EntertainmentTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email You Entered is Registered in the System.
        /// </summary>
        internal static string ErrorEmailConflictEN {
            get {
                return ResourceManager.GetString("ErrorEmailConflictEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz Eposta Sistemde Kayıtlı.
        /// </summary>
        internal static string ErrorEmailConflictTR {
            get {
                return ResourceManager.GetString("ErrorEmailConflictTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorEN {
            get {
                return ResourceManager.GetString("ErrorEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Password is Incorrect.
        /// </summary>
        internal static string ErrorLoginEN {
            get {
                return ResourceManager.GetString("ErrorLoginEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta veya Parola Yanlış.
        /// </summary>
        internal static string ErrorLoginTR {
            get {
                return ResourceManager.GetString("ErrorLoginTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Review Your Password.
        /// </summary>
        internal static string ErrorMismatchedPasswordEN {
            get {
                return ResourceManager.GetString("ErrorMismatchedPasswordEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched Password.
        /// </summary>
        internal static string ErrorMismatchedPasswordHeaderEN {
            get {
                return ResourceManager.GetString("ErrorMismatchedPasswordHeaderEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyuşmayan Parola.
        /// </summary>
        internal static string ErrorMismatchedPasswordHeaderTR {
            get {
                return ResourceManager.GetString("ErrorMismatchedPasswordHeaderTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Parolanızı Gözden Geçirin.
        /// </summary>
        internal static string ErrorMismatchedPasswordTR {
            get {
                return ResourceManager.GetString("ErrorMismatchedPasswordTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Email.
        /// </summary>
        internal static string ErrorMissingEmailEN {
            get {
                return ResourceManager.GetString("ErrorMissingEmailEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Epostanızı Girin.
        /// </summary>
        internal static string ErrorMissingEmailTR {
            get {
                return ResourceManager.GetString("ErrorMissingEmailTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Information.
        /// </summary>
        internal static string ErrorMissingHeaderEN {
            get {
                return ResourceManager.GetString("ErrorMissingHeaderEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksik Bilgi.
        /// </summary>
        internal static string ErrorMissingHeaderTR {
            get {
                return ResourceManager.GetString("ErrorMissingHeaderTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Name.
        /// </summary>
        internal static string ErrorMissingNameEN {
            get {
                return ResourceManager.GetString("ErrorMissingNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Adınızı Girin.
        /// </summary>
        internal static string ErrorMissingNameTR {
            get {
                return ResourceManager.GetString("ErrorMissingNameTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Password Again To Verify .
        /// </summary>
        internal static string ErrorMissingPasswordAgainEN {
            get {
                return ResourceManager.GetString("ErrorMissingPasswordAgainEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Şifrenizi Doğrulamak İçin Tekrar Girin.
        /// </summary>
        internal static string ErrorMissingPasswordAgainTR {
            get {
                return ResourceManager.GetString("ErrorMissingPasswordAgainTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Password.
        /// </summary>
        internal static string ErrorMissingPasswordEN {
            get {
                return ResourceManager.GetString("ErrorMissingPasswordEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Şifrenizi Girin.
        /// </summary>
        internal static string ErrorMissingPasswordTR {
            get {
                return ResourceManager.GetString("ErrorMissingPasswordTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Phone Number.
        /// </summary>
        internal static string ErrorMissingPhoneNumberEN {
            get {
                return ResourceManager.GetString("ErrorMissingPhoneNumberEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Telefon Numaranızı Girin.
        /// </summary>
        internal static string ErrorMissingPhoneNumberTR {
            get {
                return ResourceManager.GetString("ErrorMissingPhoneNumberTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Surname .
        /// </summary>
        internal static string ErrorMissingSurnameEN {
            get {
                return ResourceManager.GetString("ErrorMissingSurnameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Soyadınızı Girin.
        /// </summary>
        internal static string ErrorMissingSurnameTR {
            get {
                return ResourceManager.GetString("ErrorMissingSurnameTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string ErrorTR {
            get {
                return ResourceManager.GetString("ErrorTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Cannot Be 0!.
        /// </summary>
        internal static string ErrorYear0EN {
            get {
                return ResourceManager.GetString("ErrorYear0EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih 0 Olamaz!.
        /// </summary>
        internal static string ErrorYear0TR {
            get {
                return ResourceManager.GetString("ErrorYear0TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Cannot Be 10000!.
        /// </summary>
        internal static string ErrorYear10000EN {
            get {
                return ResourceManager.GetString("ErrorYear10000EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih 10000 Olamaz!.
        /// </summary>
        internal static string ErrorYear10000TR {
            get {
                return ResourceManager.GetString("ErrorYear10000TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitEN {
            get {
                return ResourceManager.GetString("ExitEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        internal static string ExitTR {
            get {
                return ResourceManager.GetString("ExitTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string ExpenseEN {
            get {
                return ResourceManager.GetString("ExpenseEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gider.
        /// </summary>
        internal static string ExpenseTR {
            get {
                return ResourceManager.GetString("ExpenseTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string FebruaryEN {
            get {
                return ResourceManager.GetString("FebruaryEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubat.
        /// </summary>
        internal static string FebruaryTR {
            get {
                return ResourceManager.GetString("FebruaryTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string FoodEN {
            get {
                return ResourceManager.GetString("FoodEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek.
        /// </summary>
        internal static string FoodTR {
            get {
                return ResourceManager.GetString("FoodTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string HealthEN {
            get {
                return ResourceManager.GetString("HealthEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sağlık.
        /// </summary>
        internal static string HealthTR {
            get {
                return ResourceManager.GetString("HealthTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating Bill.
        /// </summary>
        internal static string HeatingBillEN {
            get {
                return ResourceManager.GetString("HeatingBillEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isınma Faturası.
        /// </summary>
        internal static string HeatingBillTR {
            get {
                return ResourceManager.GetString("HeatingBillTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby.
        /// </summary>
        internal static string HobbyEN {
            get {
                return ResourceManager.GetString("HobbyEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobi.
        /// </summary>
        internal static string HobbyTR {
            get {
                return ResourceManager.GetString("HobbyTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeEN {
            get {
                return ResourceManager.GetString("HomeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev.
        /// </summary>
        internal static string HomeTR {
            get {
                return ResourceManager.GetString("HomeTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string IncomeEN {
            get {
                return ResourceManager.GetString("IncomeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelir.
        /// </summary>
        internal static string IncomeTR {
            get {
                return ResourceManager.GetString("IncomeTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationEN {
            get {
                return ResourceManager.GetString("InformationEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        internal static string InformationTR {
            get {
                return ResourceManager.GetString("InformationTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Bill.
        /// </summary>
        internal static string InternetBillEN {
            get {
                return ResourceManager.GetString("InternetBillEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet Faturası.
        /// </summary>
        internal static string InternetBillTR {
            get {
                return ResourceManager.GetString("InternetBillTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        internal static string InvestmentEN {
            get {
                return ResourceManager.GetString("InvestmentEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatırım.
        /// </summary>
        internal static string InvestmentTR {
            get {
                return ResourceManager.GetString("InvestmentTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string JanuaryEN {
            get {
                return ResourceManager.GetString("JanuaryEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocak.
        /// </summary>
        internal static string JanuaryTR {
            get {
                return ResourceManager.GetString("JanuaryTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string JulyEN {
            get {
                return ResourceManager.GetString("JulyEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temmuz.
        /// </summary>
        internal static string JulyTR {
            get {
                return ResourceManager.GetString("JulyTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string JuneEN {
            get {
                return ResourceManager.GetString("JuneEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haziran.
        /// </summary>
        internal static string JuneTR {
            get {
                return ResourceManager.GetString("JuneTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kid.
        /// </summary>
        internal static string KidEN {
            get {
                return ResourceManager.GetString("KidEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çocuk.
        /// </summary>
        internal static string KidTR {
            get {
                return ResourceManager.GetString("KidTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginEN {
            get {
                return ResourceManager.GetString("LoginEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginFormEN {
            get {
                return ResourceManager.GetString("LoginFormEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string LoginFormTR {
            get {
                return ResourceManager.GetString("LoginFormTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string LoginTR {
            get {
                return ResourceManager.GetString("LoginTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Money Management and Planning.
        /// </summary>
        internal static string MainFormEN {
            get {
                return ResourceManager.GetString("MainFormEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişisel Para Yönetimi ve Planlama.
        /// </summary>
        internal static string MainFormTR {
            get {
                return ResourceManager.GetString("MainFormTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string MarchEN {
            get {
                return ResourceManager.GetString("MarchEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mart.
        /// </summary>
        internal static string MarchTR {
            get {
                return ResourceManager.GetString("MarchTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string MayEN {
            get {
                return ResourceManager.GetString("MayEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayıs.
        /// </summary>
        internal static string MayTR {
            get {
                return ResourceManager.GetString("MayTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MonthEN {
            get {
                return ResourceManager.GetString("MonthEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ay.
        /// </summary>
        internal static string MonthTR {
            get {
                return ResourceManager.GetString("MonthTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameEN {
            get {
                return ResourceManager.GetString("NameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string NameTR {
            get {
                return ResourceManager.GetString("NameTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Scenario.
        /// </summary>
        internal static string NewScenarioEN {
            get {
                return ResourceManager.GetString("NewScenarioEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senaryo Oluştur.
        /// </summary>
        internal static string NewScenarioTR {
            get {
                return ResourceManager.GetString("NewScenarioTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Account.
        /// </summary>
        internal static string NoAccountEN {
            get {
                return ResourceManager.GetString("NoAccountEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Yok.
        /// </summary>
        internal static string NoAccountTR {
            get {
                return ResourceManager.GetString("NoAccountTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoEN {
            get {
                return ResourceManager.GetString("NoEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoTR {
            get {
                return ResourceManager.GetString("NoTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string NovemberEN {
            get {
                return ResourceManager.GetString("NovemberEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasım.
        /// </summary>
        internal static string NovemberTR {
            get {
                return ResourceManager.GetString("NovemberTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string OctoberEN {
            get {
                return ResourceManager.GetString("OctoberEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekim.
        /// </summary>
        internal static string OctoberTR {
            get {
                return ResourceManager.GetString("OctoberTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherEN {
            get {
                return ResourceManager.GetString("OtherEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer.
        /// </summary>
        internal static string OtherTR {
            get {
                return ResourceManager.GetString("OtherTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Again.
        /// </summary>
        internal static string PasswordAgainEN {
            get {
                return ResourceManager.GetString("PasswordAgainEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        internal static string PasswordAgainTR {
            get {
                return ResourceManager.GetString("PasswordAgainTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordEN {
            get {
                return ResourceManager.GetString("PasswordEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string PasswordTR {
            get {
                return ResourceManager.GetString("PasswordTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Care.
        /// </summary>
        internal static string PersonalCareEN {
            get {
                return ResourceManager.GetString("PersonalCareEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişisel Bakım.
        /// </summary>
        internal static string PersonalCareTR {
            get {
                return ResourceManager.GetString("PersonalCareTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet.
        /// </summary>
        internal static string PetEN {
            get {
                return ResourceManager.GetString("PetEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evcil Hayvan.
        /// </summary>
        internal static string PetTR {
            get {
                return ResourceManager.GetString("PetTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Bill.
        /// </summary>
        internal static string PhoneBillEN {
            get {
                return ResourceManager.GetString("PhoneBillEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Faturası.
        /// </summary>
        internal static string PhoneBillTR {
            get {
                return ResourceManager.GetString("PhoneBillTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumberEN {
            get {
                return ResourceManager.GetString("PhoneNumberEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string PhoneNumberTR {
            get {
                return ResourceManager.GetString("PhoneNumberTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterEN {
            get {
                return ResourceManager.GetString("RegisterEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterFormEN {
            get {
                return ResourceManager.GetString("RegisterFormEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string RegisterFormTR {
            get {
                return ResourceManager.GetString("RegisterFormTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        internal static string RegisterTR {
            get {
                return ResourceManager.GetString("RegisterTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Success.
        /// </summary>
        internal static string RegistrationSuccessEN {
            get {
                return ResourceManager.GetString("RegistrationSuccessEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Başarılı.
        /// </summary>
        internal static string RegistrationSuccessTR {
            get {
                return ResourceManager.GetString("RegistrationSuccessTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        internal static string RentEN {
            get {
                return ResourceManager.GetString("RentEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kira.
        /// </summary>
        internal static string RentTR {
            get {
                return ResourceManager.GetString("RentTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string SalaryEN {
            get {
                return ResourceManager.GetString("SalaryEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maaş.
        /// </summary>
        internal static string SalaryTR {
            get {
                return ResourceManager.GetString("SalaryTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string SaleEN {
            get {
                return ResourceManager.GetString("SaleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış.
        /// </summary>
        internal static string SaleTR {
            get {
                return ResourceManager.GetString("SaleTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string SavingEN {
            get {
                return ResourceManager.GetString("SavingEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasarruf.
        /// </summary>
        internal static string SavingTR {
            get {
                return ResourceManager.GetString("SavingTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        internal static string ScenariosEN {
            get {
                return ResourceManager.GetString("ScenariosEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senaryolar.
        /// </summary>
        internal static string ScenariosTR {
            get {
                return ResourceManager.GetString("ScenariosTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string SeptemberEN {
            get {
                return ResourceManager.GetString("SeptemberEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eylül.
        /// </summary>
        internal static string SeptemberTR {
            get {
                return ResourceManager.GetString("SeptemberTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsEN {
            get {
                return ResourceManager.GetString("SettingsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string SettingsTR {
            get {
                return ResourceManager.GetString("SettingsTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        internal static string SubscriptionEN {
            get {
                return ResourceManager.GetString("SubscriptionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonelik.
        /// </summary>
        internal static string SubscriptionTR {
            get {
                return ResourceManager.GetString("SubscriptionTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string SurnameEN {
            get {
                return ResourceManager.GetString("SurnameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        internal static string SurnameTR {
            get {
                return ResourceManager.GetString("SurnameTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string TargetEN {
            get {
                return ResourceManager.GetString("TargetEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef.
        /// </summary>
        internal static string TargetTR {
            get {
                return ResourceManager.GetString("TargetTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value.
        /// </summary>
        internal static string TargetValueEN {
            get {
                return ResourceManager.GetString("TargetValueEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef Değeri.
        /// </summary>
        internal static string TargetValueTR {
            get {
                return ResourceManager.GetString("TargetValueTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television Bill.
        /// </summary>
        internal static string TelevisionBillEN {
            get {
                return ResourceManager.GetString("TelevisionBillEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Televizyon Faturası.
        /// </summary>
        internal static string TelevisionBillTR {
            get {
                return ResourceManager.GetString("TelevisionBillTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalEN {
            get {
                return ResourceManager.GetString("TotalEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expense.
        /// </summary>
        internal static string TotalExpenseEN {
            get {
                return ResourceManager.GetString("TotalExpenseEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Gider.
        /// </summary>
        internal static string TotalExpenseTR {
            get {
                return ResourceManager.GetString("TotalExpenseTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income.
        /// </summary>
        internal static string TotalIncomeEN {
            get {
                return ResourceManager.GetString("TotalIncomeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Gelir.
        /// </summary>
        internal static string TotalIncomeTR {
            get {
                return ResourceManager.GetString("TotalIncomeTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        internal static string TotalTR {
            get {
                return ResourceManager.GetString("TotalTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string TransportEN {
            get {
                return ResourceManager.GetString("TransportEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulaşım.
        /// </summary>
        internal static string TransportTR {
            get {
                return ResourceManager.GetString("TransportTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        internal static string TravelEN {
            get {
                return ResourceManager.GetString("TravelEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seyahat.
        /// </summary>
        internal static string TravelTR {
            get {
                return ResourceManager.GetString("TravelTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeEN {
            get {
                return ResourceManager.GetString("TypeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tür.
        /// </summary>
        internal static string TypeTR {
            get {
                return ResourceManager.GetString("TypeTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Bill.
        /// </summary>
        internal static string WaterBillEN {
            get {
                return ResourceManager.GetString("WaterBillEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su Faturası.
        /// </summary>
        internal static string WaterBillTR {
            get {
                return ResourceManager.GetString("WaterBillTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string WeekEN {
            get {
                return ResourceManager.GetString("WeekEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hafta.
        /// </summary>
        internal static string WeekTR {
            get {
                return ResourceManager.GetString("WeekTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YearEN {
            get {
                return ResourceManager.GetString("YearEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl.
        /// </summary>
        internal static string YearTR {
            get {
                return ResourceManager.GetString("YearTR", resourceCulture);
            }
        }
    }
}
